#+TITLE: PHP E-invoice It

A PHP package for managing italian e-invoice and notice XML formats.

Please refer to
- [[https://github.com/taocomp/php-sdicoop-server][PHP SdICoop - Server]] for implementing web services required by the Italian Exchange System (aka "SdI")
- [[https://github.com/taocomp/php-sdicoop-client][PHP SdICoop - Client]] to connect to SdI web services

See [[https://forum.italia.it/c/fattura-pa][Forum Italia - Fatturazione Elettronica]] for server configuration, interoperability tests, etc. In particular:
- Apache configuration :: [[https://forum.italia.it/t/accreditamento-sdicoop-configurazione-ssl-su-apache/3314][Accreditamento SDICoop: configurazione SSL su Apache - Fatturazione Elettroni...]]
- Interoperability tests :: [[https://forum.italia.it/t/test-interoperabilita-soluzioni/4370][Test Interoperabilità Soluzioni - Fatturazione Elettronica - Forum Italia]]

If you need a "ready to start" solution, or a consultancy for your PHP project, please feel free to contact us at [[mailto:e-invoicing@taocomp.com][e-invoicing@taocomp.com]].

* Quickstart
** Dependencies
~php-xml~.

** Invoice
*** Create a new invoice
Create a new FPA12 invoice:
#+BEGIN_SRC 
$invoice = new FatturaElettronica('FPA12');
#+END_SRC

Create a new FPR12 invoice:
#+BEGIN_SRC 
$invoice = new FatturaElettronica('FPR12');
#+END_SRC

*** Load an invoice from file
#+BEGIN_SRC 
$invoice->load('/path/to/invoice.xml');
#+END_SRC

Please note that if you create an FPR12 invoice and then load an FPA12 invoice (or viceversa), an exception is thrown.

To force loading:
#+BEGIN_SRC 
$ignoreVersion = true;
$invoice->load('/path/to/invoice.xml', 0, $ignoreVersion);
#+END_SRC

*** Invoice lot and line items
Set 2 bodies:
#+BEGIN_SRC 
$invoice->setLotSize(2);
#+END_SRC

Set 3 line items for second body:
#+BEGIN_SRC 
$invoice->setLineItemCount(3, 2);
#+END_SRC

*** Set values
Set single value:
#+BEGIN_SRC 
$invoice->setValue('ProgressivoInvio', 10001);
#+END_SRC

Set values via-array:
#+BEGIN_SRC 
$invoice->setValues('IdTrasmittente', array(
    'IdCodice' => '09876543210',
    'IdPaese' => 'IT'
));
#+END_SRC

#+BEGIN_SRC 
$invoice->setValues('CedentePrestatore/Sede', array(
    'Indirizzo' => 'VIA UNIVERSO 1'
));
#+END_SRC

#+BEGIN_SRC 
$invoice->setValues('CessionarioCommittente', array(
    // CessionarioCommittente/DatiAnagrafici/CodiceFiscale
    'DatiAnagrafici/CodiceFiscale' => '01234567890',
    // Denominazione, somewhere inside CessionarioCommittente
    './/Denominazione' => 'BETA SRL'
));
#+END_SRC

#+BEGIN_SRC 
// Set values for second body
$body2 = $invoice->getBody(2);
$invoice->setValue('.//Numero', 44, $body2);
$invoice->setValue('.//Data', '2018-12-12', $body2);
#+END_SRC

Set multiple values at once:
#+BEGIN_SRC 
$invoice->setValuesAll('DatiGenerali', array(
    // All "RiferimentoNumeroLinea" somewhere inside DatiGenerali
    './/RiferimentoNumeroLinea' => 1,
    // All "IdDocumento" somewhere inside DatiGenerali
    './/IdDocumento' => 4455,
    // All "NumItem" somewhere inside DatiGenerali
    './/NumItem' => 1
));
#+END_SRC

*** Save invoice
Set an optional default destination dir for all invoices:
#+BEGIN_SRC 
FatturaElettronica::setDefaultPrefixPath('path/to/dir');
#+END_SRC

Set an optional destination dir for current invoice:
#+BEGIN_SRC 
$invoice->setPrefixPath('path/to/another/dir');
#+END_SRC

Save invoice:
#+BEGIN_SRC 
$invoice->save();
#+END_SRC

** Notices
*** Create a new notice
NotificaEsitoCommittente:
#+BEGIN_SRC 
$notice = new EsitoCommittente();
#+END_SRC

*** Load a notice from file
*** Set values
#+BEGIN_SRC 
// Set some values from invoice, second body:
$notice->setValuesFromInvoice($invoice, 2);

// Set values
$notice->setValue('IdentificativoSdI', 1234567);
$notice->setValue('Esito', EsitoCommittente::EC01);
#+END_SRC

*** Save notice
#+BEGIN_SRC 
// Set filename from invoice
$notice->setFilenameFromInvoice($invoice, '_EC_001');

// Save notice
$notice->save();
#+END_SRC

* Credits
We want to thank all contributors of [[https://forum.italia.it/c/fattura-pa][Forum Italia - Fatturazione Elettronica]] who have shared their snippets and any available info.

* License
GPLv3.
